# Generated by Django 4.1.2 on 2022-11-21 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdkarWithTalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/adkarWithTalo/')),
                ('isAdkar', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('readingCount', models.IntegerField(default=1)),
                ('readingTime', models.TimeField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginPageImage', models.ImageField(default='/media/images/login-background.jpeg', upload_to='images/shikh')),
                ('subscriptionPrice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProbQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('questionsCount', models.IntegerField(default=1)),
                ('desc', models.TextField(default='')),
                ('moreTrueDesc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('price', models.FloatField(default=3)),
                ('desc', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='subax', max_length=255)),
                ('fromTime', models.TimeField(null=True)),
                ('toTime', models.TimeField(null=True)),
                ('notificationTime', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShikhCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(blank=True, default='https://st3.depositphotos.com/9998432/13335/v/600/depositphotos_133352062-stock-illustration-default-placeholder-profile-icon.jpg', null=True, upload_to='images/shikh')),
                ('isHero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('number', models.CharField(default=0, max_length=16, unique=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/userProfile')),
                ('city', models.CharField(default='Mogadishu', max_length=33)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=15)),
                ('aboutUser', models.TextField(blank=True, null=True)),
                ('isSingle', models.BooleanField(default=True)),
                ('numberOfWives', models.IntegerField(default=0)),
                ('numberOfChilds', models.IntegerField(default=0)),
                ('yearsOfPain', models.IntegerField(default=0)),
                ('latestSbscriptionDateFrom', models.DateField(blank=True, null=True)),
                ('latestSbscriptionDateTo', models.DateField(blank=True, null=True)),
                ('inPending', models.BooleanField(default=True)),
                ('isSubscribedUser', models.BooleanField(default=False)),
                ('subscriptionActive', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=False)),
                ('userMatchedAdkarWithTalo', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProductsRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRoutine', models.BooleanField(default=False)),
                ('fromDate', models.DateField(default=datetime.datetime(2022, 11, 21, 13, 28, 14, 780035))),
                ('toDate', models.DateField(default=datetime.datetime(2022, 11, 23, 13, 28, 14, 780035))),
                ('theProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('usageTimes', models.ManyToManyField(blank=True, null=True, to='api.routinetime')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trueAnswers', models.IntegerField(default=0)),
                ('falseAnswers', models.IntegerField(default=0)),
                ('thePorbQuestionCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProbQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.CharField(default='', max_length=255)),
                ('arb', models.CharField(default='', max_length=255)),
                ('eng', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('regDate', models.DateField(auto_now=True)),
                ('isTrueAdkarWithTaloyin', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
                ('isTrueProducts', models.ManyToManyField(blank=True, null=True, to='api.productinfo')),
                ('probQuestionCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProbAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('answer', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('theProbQuestion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.probquestion')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('orderTime', models.DateTimeField(auto_now=True)),
                ('userTaked', models.BooleanField(default=False)),
                ('paidedMoney', models.FloatField(default=0)),
                ('userTakedTime', models.DateTimeField(blank=True, null=True)),
                ('paymentMethod', models.CharField(default='EVC WAAFI-PAYMENT', max_length=255)),
                ('discount', models.FloatField(default=0)),
                ('theProductInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningCilajWithQuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/listeningCilajWithQuran/')),
                ('text', models.TextField(default='')),
                ('theShikh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shikhcategory')),
            ],
        ),
    ]
