# Generated by Django 4.1.2 on 2024-01-01 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdkarWithTalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/adkarWithTalo/')),
                ('isAdkar', models.BooleanField(default=False)),
                ('itsArabic', models.BooleanField(default=True)),
                ('text', models.TextField(default='')),
                ('readingCount', models.IntegerField(default=1)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255)),
                ('meetinTime', models.CharField(default='01:00 saac', max_length=255)),
                ('bookingPrice', models.FloatField(default=5)),
                ('fullDesc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProbQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('questionsCount', models.IntegerField(default=1)),
                ('desc', models.TextField(default='')),
                ('moreTrueDesc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isRoutine', models.BooleanField(default=True)),
                ('theMessageText', models.TextField(default='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('price', models.FloatField(default=3)),
                ('desc', models.TextField(blank=True, null=True)),
                ('dateRegistred', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='subax', max_length=255)),
                ('fromTime', models.TimeField(null=True)),
                ('toTime', models.TimeField(null=True)),
                ('notificationTime', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShikhCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/shikh')),
                ('simDesc', models.TextField(default='')),
                ('isHero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WaafiMarchentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantUid', models.CharField(default='', max_length=255)),
                ('apiUserId', models.CharField(default='', max_length=255)),
                ('apiKey', models.CharField(default='', max_length=255)),
                ('merchantUidCABDALLA', models.CharField(default='', max_length=255)),
                ('apiUserIdCABDALLA', models.CharField(default='', max_length=255)),
                ('apiKeyCABDALLA', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('number', models.CharField(default=0, max_length=16, unique=True)),
                ('fireMessageId', models.CharField(default='', max_length=1000)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images/userProfile')),
                ('city', models.CharField(default='Mogadishu', max_length=33)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=15)),
                ('aboutUser', models.TextField(blank=True, null=True)),
                ('socialSituation', models.CharField(default='DOOB', max_length=25)),
                ('numberOfWives', models.IntegerField(default=0)),
                ('numberOfChilds', models.IntegerField(default=0)),
                ('yearsOfPain', models.IntegerField(default=0)),
                ('latestTimeAnsweredQuestion', models.DateField(blank=True, null=True)),
                ('latestSbscriptionDateFrom', models.DateField(blank=True, null=True)),
                ('latestSbscriptionDateTo', models.DateField(blank=True, null=True)),
                ('inPending', models.BooleanField(default=False)),
                ('isSubscribedUser', models.BooleanField(default=False)),
                ('subscriptionActive', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=False)),
                ('userMatchedAdkarWithTalo', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProductsRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRoutine', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('isTakedProduct', models.BooleanField(default=False)),
                ('fromDate', models.DateField(default=datetime.datetime(2024, 1, 1, 13, 23, 7, 205715))),
                ('toDate', models.DateField(default=datetime.datetime(2024, 1, 3, 13, 23, 7, 205715))),
                ('theProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('usageTimes', models.ManyToManyField(blank=True, null=True, to='api.routinetime')),
            ],
        ),
        migrations.CreateModel(
            name='UserChildAnswerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(default='', max_length=255)),
                ('trueAnswers', models.IntegerField(default=0)),
                ('falseAnswers', models.IntegerField(default=0)),
                ('thePorbQuestionCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserChildAdkarWithProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(default='', max_length=255)),
                ('childMatchedAdkarWithTalo', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
                ('theProducts', models.ManyToManyField(blank=True, null=True, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trueAnswers', models.IntegerField(default=0)),
                ('falseAnswers', models.IntegerField(default=0)),
                ('thePorbQuestionCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SendNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('notificationType', models.CharField(choices=[('ORDER', 'ORDER'), ('DOCTOR-APPOINTMENT', 'DOCTOR-APPOINTMENT'), ('PRODUCT-IN-THE-BUG', 'PRODUCT-IN-THE-BUG'), ('PATIENT-RESULT', 'PATIENT-RESULT')], default='ORDER', max_length=255)),
                ('isLocalNotification', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInTheBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('isTaked', models.BooleanField(default=False)),
                ('theProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUsageTimes', models.ManyToManyField(blank=True, null=True, to='api.routinetime')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='productinfo',
            name='theUsageTimes',
            field=models.ManyToManyField(blank=True, null=True, to='api.routinetime'),
        ),
        migrations.CreateModel(
            name='ProbQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuucaSuaasha', models.CharField(choices=[('caruur', 'CARUUR'), ('dadwaawayn', 'DADWAAWAYN')], default='dadwaawayn', max_length=255)),
                ('som', models.CharField(default='', max_length=255)),
                ('arb', models.CharField(default='', max_length=255)),
                ('eng', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('regDate', models.DateField(auto_now=True)),
                ('isTrueAdkarWithTaloyin', models.ManyToManyField(to='api.adkarwithtalo')),
                ('isTrueProducts', models.ManyToManyField(blank=True, null=True, to='api.productinfo')),
                ('probQuestionCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProbAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('answer', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('theProbQuestion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.probquestion')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultTitle', models.CharField(default='JAWAABTA BAARINTAANKA', max_length=255)),
                ('resultDesc', models.TextField(default='')),
                ('latestResult', models.BooleanField(default=True)),
                ('resultDate', models.DateTimeField()),
                ('adkarsWithTalos', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
                ('routineProducts', models.ManyToManyField(blank=True, null=True, to='api.userproductsroutine')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=25)),
                ('orderTime', models.DateTimeField(auto_now=True)),
                ('deliveredTime', models.DateTimeField(blank=True, null=True)),
                ('isFromBug', models.BooleanField(default=False)),
                ('userTaked', models.BooleanField(default=False)),
                ('paidedMoney', models.FloatField(default=0)),
                ('userTakedTime', models.DateTimeField(blank=True, null=True)),
                ('paymentMethod', models.CharField(default='EVC WAAFI-PAYMENT', max_length=255)),
                ('discount', models.FloatField(default=0)),
                ('theProductInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
        migrations.CreateModel(
            name='ListeningCilajWithQuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isVideo', models.BooleanField(default=False)),
                ('videoLink', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('voiceLink', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice/listeningCilajWithQuran/')),
                ('text', models.TextField(default='')),
                ('theShikh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhagaysigaWithMuqaalkaShiiqa', to='api.shikhcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAssignedDated', models.DateField(blank=True, null=True)),
                ('doctorAssignedDated', models.DateTimeField(blank=True, null=True)),
                ('sessionEnded', models.BooleanField(default=False)),
                ('appointmentMeetingLink', models.CharField(blank=True, max_length=255, null=True)),
                ('userRate', models.IntegerField(default=3)),
                ('theCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointmentcategory')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['-sessionEnded'],
            },
        ),
        migrations.CreateModel(
            name='ChildProbAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('answer', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('theProbQuestion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.probquestion')),
                ('theUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AppInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginPageImage', models.ImageField(blank=True, null=True, upload_to='images/appInfo')),
                ('fmLink', models.CharField(default='', max_length=10000)),
                ('contactNumber', models.CharField(default='252619820834', max_length=20)),
                ('youSearchedText', models.CharField(max_length=500)),
                ('isThereDiscount', models.BooleanField(default=False)),
                ('discountSubscriptionPrice', models.FloatField(default=5)),
                ('subscriptionPrice', models.FloatField(default=7)),
                ('subscriptionPageTitle', models.CharField(default='', max_length=255)),
                ('subscriptionPageImage', models.ImageField(blank=True, null=True, upload_to='images/appInfo')),
                ('subscriptionPageVideoLink', models.CharField(default='', max_length=3000)),
                ('subscriptionButtonTitle', models.CharField(default='', max_length=100)),
                ('subscriptionButtonDesc', models.CharField(default='', max_length=255)),
                ('doctorWorkingForYouText', models.CharField(default='', max_length=255)),
                ('subscriptionFeatures', models.ManyToManyField(to='api.subscriptionfeatures')),
            ],
        ),
        migrations.AddField(
            model_name='adkarwithtalo',
            name='readingTime',
            field=models.ManyToManyField(blank=True, null=True, to='api.routinetime'),
        ),
    ]
