# Generated by Django 4.1.2 on 2022-11-22 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shikhcategory_simdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shikhcategory',
            name='simDesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 13, 22, 19, 414322)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 13, 22, 19, 414322)),
        ),
    ]
