# Generated by Django 4.1.2 on 2022-11-22 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 14, 38, 19, 308418)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 14, 38, 19, 308418)),
        ),
    ]
