# Generated by Django 4.1.2 on 2022-11-22 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcategory',
            name='meetinTime',
            field=models.CharField(default='01:00 saac', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 22, 14, 42, 7, 624018)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 14, 42, 7, 625019)),
        ),
    ]
