# Generated by Django 4.1.2 on 2022-11-23 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='appinformation',
            name='discountSubscriptionPrice',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='doctorWorkingForYouText',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='isThereDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionPageImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/appInfo'),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionPageTitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionPageVideoLink',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='youSearchedText',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appinformation',
            name='loginPageImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/appInfo'),
        ),
        migrations.AlterField(
            model_name='appinformation',
            name='subscriptionPrice',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 8, 37, 43, 189509)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 8, 37, 43, 189509)),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionFeatures',
            field=models.ManyToManyField(to='api.subscriptionfeatures'),
        ),
    ]
