# Generated by Django 4.1.2 on 2022-11-23 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subscriptionfeatures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctorAssignedDated',
            field=models.DateTimeField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='userAssignedDated',
            field=models.DateTimeField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 15, 15, 16, 456307)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 15, 15, 16, 456307)),
        ),
    ]
