# Generated by Django 4.1.2 on 2022-11-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productinfo_isroutine_productinfo_theusagetimes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='userAssignedDated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 16, 30, 53, 315730)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 30, 16, 30, 53, 315730)),
        ),
    ]
