# Generated by Django 4.1.2 on 2022-11-29 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_doctorappointment_userassigneddated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionButtonDesc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appinformation',
            name='subscriptionButtonTitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 7, 38, 42, 455493)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 7, 38, 42, 455493)),
        ),
        migrations.CreateModel(
            name='ProductsInTheBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('isTaked', models.BooleanField(default=False)),
                ('theProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
