# Generated by Django 4.1.2 on 2022-11-29 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='theMessageText',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 15, 55, 53, 612846)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 15, 55, 53, 612846)),
        ),
    ]
