# Generated by Django 4.1.2 on 2022-11-29 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adkarwithtalo',
            name='readingTime',
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 17, 0, 39, 391284)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 17, 0, 39, 391284)),
        ),
        migrations.AddField(
            model_name='adkarwithtalo',
            name='readingTime',
            field=models.ManyToManyField(blank=True, null=True, to='api.routinetime'),
        ),
    ]
