# Generated by Django 4.1.2 on 2022-11-29 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_adkarwithtalo_readingtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkarwithtalo',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 21, 47, 29, 889961)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 21, 47, 29, 889961)),
        ),
    ]
