# Generated by Django 4.1.2 on 2022-12-22 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probquestion',
            name='nuucaSuaasha',
            field=models.CharField(choices=[('caruur', 'CARUUR'), ('dadwaawayn', 'DADWAAWAYN')], default='dadwaawayn', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 11, 14, 7, 761524)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 24, 11, 14, 7, 761524)),
        ),
    ]
