# Generated by Django 4.1.2 on 2022-12-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_doctorappointment_appointmentmeetinglink_and_more'),
        ('api', '0024_probquestion_nuucasuaasha_and_more'),
    ]

    operations = [
    ]
