# Generated by Django 4.1.2 on 2022-12-22 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20221222_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductsroutine',
            name='isTakedProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 11, 47, 10, 590888)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 24, 11, 47, 10, 590888)),
        ),
    ]
