# Generated by Django 4.1.2 on 2022-12-22 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userproductsroutine_istakedproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 13, 49, 6, 961685)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 24, 13, 49, 6, 961685)),
        ),
        migrations.CreateModel(
            name='ChildProbAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('answer', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('theProbQuestion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.probquestion')),
            ],
        ),
    ]
