# Generated by Django 4.1.2 on 2022-12-22 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprobanswer',
            name='theUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 14, 3, 51, 687330)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 24, 14, 3, 51, 688329)),
        ),
    ]
