# Generated by Django 4.1.2 on 2022-12-25 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_childprobanswer_theuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isSingle',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='socialSituation',
            field=models.CharField(default='DOOB', max_length=25),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 25, 11, 16, 23, 711319)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 11, 16, 23, 711319)),
        ),
    ]
