# Generated by Django 4.1.2 on 2022-12-25 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_userprofile_issingle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 25, 20, 23, 10, 155985)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 20, 23, 10, 155985)),
        ),
        migrations.CreateModel(
            name='UserChildAnswerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(default='', max_length=255)),
                ('trueAnswers', models.IntegerField(default=0)),
                ('falseAnswers', models.IntegerField(default=0)),
                ('thePorbQuestionCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.probquestioncategory')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
