# Generated by Django 4.1.2 on 2023-01-01 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 18, 7, 30, 568637)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 18, 7, 30, 568637)),
        ),
        migrations.CreateModel(
            name='UserChildAdkarWithProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theChild', models.CharField(default='', max_length=255)),
                ('theAdkars', models.ManyToManyField(to='api.adkarwithtalo')),
                ('theProducts', models.ManyToManyField(to='api.productinfo')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
