# Generated by Django 4.1.2 on 2023-01-01 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchildadkarwithproduct',
            name='theAdkars',
            field=models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo'),
        ),
        migrations.AlterField(
            model_name='userchildadkarwithproduct',
            name='theProducts',
            field=models.ManyToManyField(blank=True, null=True, to='api.productinfo'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 1, 18, 56, 9, 320791)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 18, 56, 9, 320791)),
        ),
    ]
