# Generated by Django 4.1.2 on 2023-01-14 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_theadkars_userchildadkarwithproduct_childmatchedadkarwithtalo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fireMessageId',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 14, 18, 1, 13, 151331)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 18, 1, 13, 151331)),
        ),
    ]
