# Generated by Django 4.1.2 on 2023-01-16 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 17, 29, 32, 758093)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 17, 29, 32, 758093)),
        ),
    ]
