# Generated by Django 4.1.2 on 2023-01-25 15:19

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkarwithtalo',
            name='voice',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 25, 18, 19, 28, 186070)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 27, 18, 19, 28, 186070)),
        ),
    ]
