# Generated by Django 4.1.2 on 2023-01-25 15:20

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_adkarwithtalo_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adkarwithtalo',
            name='voice',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 25, 18, 20, 46, 861430)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 27, 18, 20, 46, 861430)),
        ),
    ]
