# Generated by Django 4.1.2 on 2023-01-27 07:38

import cloudinary_storage.storage
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_adkarwithtalo_voice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorappointment',
            options={'ordering': ['-sessionEnded']},
        ),
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['-userTaked']},
        ),
        migrations.AlterField(
            model_name='listeningcilajwithquran',
            name='voice',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='voice/listeningCilajWithQuran/'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 27, 10, 38, 33, 428520)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 29, 10, 38, 33, 428520)),
        ),
    ]
