# Generated by Django 4.1.2 on 2023-01-27 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_productinfo_dateregistred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinformation',
            name='fmLink',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 27, 11, 43, 52, 561078)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 29, 11, 43, 52, 561078)),
        ),
    ]
