# Generated by Django 4.1.2 on 2023-02-16 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_orderedproduct_deliveredtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningcilajwithquran',
            name='isVideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningcilajwithquran',
            name='videoLink',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='listeningcilajwithquran',
            name='voiceLink',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='listeningcilajwithquran',
            name='theShikh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhagaysigaShiiqa', to='api.shikhcategory'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 10, 3, 56, 972373)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 10, 3, 56, 972373)),
        ),
    ]
