# Generated by Django 4.1.2 on 2023-02-25 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 18, 5, 47, 774571)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 27, 18, 5, 47, 774571)),
        ),
    ]
