# Generated by Django 4.1.2 on 2023-02-25 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waafimarchentconfig',
            name='apiKeyCABDALLA',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='waafimarchentconfig',
            name='apiUserIdCABDALLA',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='waafimarchentconfig',
            name='merchantUidCABDALLA',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 18, 16, 47, 952992)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 2, 27, 18, 16, 47, 952992)),
        ),
    ]
