# Generated by Django 4.1.2 on 2023-03-09 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_waafimarchentconfig_apikeycabdalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latestMonthAnsweredQuestion',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latestTimeAnsweredQuestion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 22, 14, 27, 171175)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 22, 14, 27, 171175)),
        ),
    ]
