# Generated by Django 4.1.2 on 2023-03-09 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_userprofile_latestmonthansweredquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 22, 20, 38, 242434)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 22, 20, 38, 242434)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latestTimeAnsweredQuestion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
