# Generated by Django 4.1.2 on 2023-10-08 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='isFromBug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsinthebug',
            name='theUsageTimes',
            field=models.ManyToManyField(blank=True, null=True, to='api.routinetime'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 18, 25, 40, 409306)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 18, 25, 40, 409306)),
        ),
    ]
