# Generated by Django 4.1.2 on 2023-10-12 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_userproductsroutine_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probquestion',
            name='isTrueAdkarWithTaloyin',
            field=models.ManyToManyField(to='api.adkarwithtalo'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 11, 3, 28, 647394)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 11, 3, 28, 647394)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inPending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultTitle', models.CharField(default='JAWAABTA BAARINTAANKA', max_length=255)),
                ('resultDesc', models.TextField(default='')),
                ('resultDate', models.DateTimeField()),
                ('adkarsWithTalos', models.ManyToManyField(blank=True, null=True, to='api.adkarwithtalo')),
                ('routineProducts', models.ManyToManyField(blank=True, null=True, to='api.userproductsroutine')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
