# Generated by Django 4.1.2 on 2023-10-12 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_probquestion_istrueadkarwithtaloyin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientresult',
            name='latestResult',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 11, 7, 50, 573015)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 11, 7, 50, 573015)),
        ),
    ]
