# Generated by Django 4.1.2 on 2023-10-24 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_patientresult_latestresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnotification',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sendnotification',
            name='notificationType',
            field=models.CharField(default='ORDER', max_length=255),
        ),
        migrations.AlterField(
            model_name='sendnotification',
            name='theUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 14, 24, 37, 14339)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 14, 24, 37, 14339)),
        ),
    ]
