# Generated by Django 4.1.2 on 2023-10-24 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_sendnotification_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinformation',
            name='contactNumber',
            field=models.CharField(default='252619820834', max_length=20),
        ),
        migrations.AlterField(
            model_name='sendnotification',
            name='notificationType',
            field=models.CharField(choices=[('ORDER', 'ORDER'), ('DOCTOR-APPOINTMENT', 'DOCTOR-APPOINTMENT'), ('PRODUCT-IN-THE-BUG', 'PRODUCT-IN-THE-BUG'), ('PATIENT-RESULT', 'PATIENT-RESULT')], default='ORDER', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 20, 35, 45, 815797)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 20, 35, 45, 815797)),
        ),
    ]
