# Generated by Django 4.1.2 on 2023-10-28 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_appinformation_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductsroutine',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 28, 21, 2, 11, 733704)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 10, 30, 21, 2, 11, 733704)),
        ),
    ]
