# Generated by Django 4.1.2 on 2023-11-03 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_userproductsroutine_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientresult',
            name='resultDesc',
            field=models.TextField(default='', max_length=555555555),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 20, 12, 37, 512889)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 20, 12, 37, 512889)),
        ),
    ]
