# Generated by Django 4.1.2 on 2023-11-03 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_patientresult_resultdesc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ['-status']},
        ),
        migrations.AlterField(
            model_name='patientresult',
            name='resultDesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='fromDate',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 20, 27, 37, 439359)),
        ),
        migrations.AlterField(
            model_name='userproductsroutine',
            name='toDate',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 20, 27, 37, 439359)),
        ),
    ]
